# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68215c1e07b773479c31e60f24276fe9c3dbd1495403c52f63ff7680412e794b64470a3126292892c8c035ec16aa053a8d9878a8de94ad778836acb462aa0f8e

test:
  secret_key_base: 5ab77ce1844a39bf8f01fee8b61539fed4432d5ee6903c224a803af33d5b17e2b09ae029b755854efa590caf429abc0e9db4cdf6429bba1375ff052108a30bc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
